apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp              # мітка Pod по якому вона буде зв'язана з Deployment та Service
      annotations:
        # vault.hashicorp.com/agent-inject: "true"
        # vault.hashicorp.com/tls-skip-verify: "true"
        # vault.hashicorp.com/agent-inject-secret-db_auth: "secret/db_auth"
        # vault.hashicorp.com/agent-inject-template-db_auth: |
        #   {{- with secret "secret/db_auth" -}}
        #   {
        #     "username" : "{{ .Data.username }}",
        #     "password" : "{{ .Data.password }}"
        #   }
        #   {{- end }}
        # vault.hashicorp.com/role: "webapp"
    
    spec:
      serviceAccountName: vault
      containers:
        - image: consumer
          imagePullPolicy: Never
          name: webapp           # ім'я контейнеру
          env:            
            - name: VAULT_ADDR              
              value: 'http://vault:8200'            
            - name: JWT_PATH              
              value: '/var/run/secrets/kubernetes.io/serviceaccount/token'           
            - name: SERVICE_PORT              
              value: '8080'
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди

---

apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
  selector:
    app: webapp      # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу

# ---

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: basic-secret
#   labels:
#     app: consumer   