apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-js-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: service-js
  template:
    metadata:
     labels:
       app: service-js              # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: avovchenko01/lab1-js-server
          name: service-js           # ім'я контейнеру
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди

---

apiVersion: v1
kind: Service
metadata:
  name: service-js-service
spec:
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
  selector:
    app: service-js      # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу

